### ISSUE TITLE
Documentation fails to build on GHC 7

### ISSUE THREAD

**Issue by bmillwood** [vincenthz/hs-tls-extra#2]
As you can see on hackage, the haddock step fails during the install process:

http://hackage.haskell.org/packages/archive/tls-extra/0.1.6/logs/failure/ghc-7.0

It seems that a comment sequence starting -- \* causes the failure, of which there are two in Network/TLS/Extra/Certificate.hs

Fixing these two comments (inserting a word in the beginning, for example) allows the rest of the docs to build.

This is also causing the docs of e.g. http-enumerator to fail to build on Hackage, so a new release after the bug is fixed would be useful :)

**Comment by vincenthz** [comment]
i've fixed it now in tls-extra-0.1.7, thanks for the report.
