### ISSUE TITLE
tls-extra on OSX

### ISSUE THREAD

**Issue by konn** [vincenthz/hs-tls-extra#3]
Hi,

The latest version of certificate package supports Mac OS X, so I think Line 49 in tls-extra.cabal:

>  if os(windows) || os(osx)

should be:

>  if os(windows)

**Comment by vincenthz** [comment]
Hi, did you test the change ?

I was holding on this change, until someone verified the certificate checking with tls-extra work end-to-end (using http-enumerator or the example stunnel)

**Comment by luite** [comment]
It does not work, there are a few issues with the code in certificate.
- It reads the user keychain, which usually doesn't contain much. You probably want to read the system keychain: "security find-certificate -pa /System/Library/Keychains/SystemRootCertificates.keychain" (or maybe SystemCACertificates.keychain, I'm not sure)
- It calls waitForProcess before reading the output, so it will hang indefinitely if the output doesn't fit in the buffer

**Comment by vincenthz** [comment]
thanks @luite. Any chance you can make those changes to certificate ? unfortunately I don't have any OSX to test, so i will have to rely on contribution for this feature. it would be nice to see certificate checking activated on every major platforms.

**Comment by luite** [comment]
I'll try to do it in the next few days, but I'd like to check first what the right keychain file for this is, and whether to include the user keychain. (I think it's possible to encrypt the user keychain with a different password than the login password, so I'm not sure if it's always possible to open it)
